plugins { id 'com.android.application' }
android {
    namespace "com.example.haterhunter"
    compileSdk 34
    defaultConfig {
        applicationId "com.example.haterhunter"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "1.0.2"
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
